config/routes.rb
AtddAgileGuru::Application.routes.draw do
    resources :items
    resources :questions
    resources :answers

end

app/models/answer.rb
class Answer < ActiveRecord::Base
    validates_presence_of :text
    attr_accessible :text
    belongs_to :question
end

app/models/item.rb
class Item < ActiveRecord::Base
    validates_presence_of :text
    attr_accessible :text
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :contents
  attr_accessible :contents
  has_many :answers, :dependent => :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    
    def new
        @question = Question.find(params[:question_id].to_i)
        @answer = Answer.new
    end
    
    def create
        answer = Answer.new(params[:answer])
        answer.question = Question.find(params[:question_id].to_i)
        answer.save
        redirect_to :controller => "questions", :action => "index"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    
    def index
        Item.find_in_batches do |items|
            @items = items
        end
    end
    
    def new
        @item = Item.new
    end
    
    def create
        item = Item.new(params[:item])
        item.save
        redirect_to :action => "index"
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    
    def index
        Question.find_in_batches do |questions|
            @questions = questions
        end
    end
    
    def new
        @question = Question.new
    end
    
    def create
        question = Question.new(params[:question])
        question.save
        redirect_to :action => "index"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.erb
<h2><%= @question.contents %></h2>

<%= form_for @answer do |f| %>
    <%= f.text_area :text %>
    <%= hidden_field_tag("question_id", "#{@question.id}") %>
    <%= f.submit "Add" %>
<% end %>

app/views/items/index.html.erb
<% for item in @items %>
<p><%= item.text  %></p>
<% end %>

app/views/items/new.html.erb
<%= form_for @item do |f| %>
    <%= f.text_field :text %>
    <%= f.submit "Save" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AtddAgileGuru</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<% for question in @questions %>
<div class="question">
<p><%= question.contents %>&nbsp;<%= link_to "Answer",new_answer_path(:question_id => question.id) %></p>
<% for answer in question.answers %>
<p class="answer"><%= answer.text %></p>
<% end %>
</div>
<% end %>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
    <%= f.text_area :contents %>
    <%= f.submit "Save" %>
<% end %>